name: Deploy All Function Apps

on:
  push:
    branches:
      - main

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-matrix.outputs.apps }}
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: |
          # Find subfolders containing host.json (marks a Function App project)
          folders=$(find . -maxdepth 1 -type d ! -name ".github" ! -name "." | sed 's|./||')
          echo "Found folders: $folders"

          json="["
          for f in $folders; do
            if [ -f "$f/host.json" ]; then
              json="$json\"$f\","
            fi
          done
          json="${json%,}]"
          echo "apps=$json" >> $GITHUB_OUTPUT

  deploy:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.discover.outputs.apps) }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.folder }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          # Assumes your Azure Function App name matches the folder name
          app-name: ${{ matrix.folder }}
          package: ${{ matrix.folder }}
        env:
          # Each Function App needs its own publish profile secret
          AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets[matrix.folder | upper]_PUBLISH_PROFILE }}
